import Header from './Header'

const secciones = [
  { h: '1. ¿Que significa ser Experto?', p: ['Un Experto es una persona natural o jurídica que utiliza la plataforma Expertos para presentar sus conocimientos, experiencia, habilidades o servicios profesionales y conectarse con personas o empresas que puedan requerirlos.', 'Ser Experto dentro de la plataforma no significa que Expertos sea su empleador, representante, socio, agente o subordinado.', 'Cada Experto presta sus servicios de manera independiente y es responsable de las obligaciones que se deriven de su actividad profesional.'] },
  { h: '2. Información del perfil', p: ['El Experto debe proporcionar información:'], ul: ['Verdadera.', 'Completa.', 'Clara.', 'Actualizada.', 'Comprobable cuando corresponda.'], p2: ['El perfil podrá incluir información como nombre, fotografia, profesión, experiencia, formación académica, especialidades, habilidades, certificaciones, servicios ofrecidos, portafolio, descripción profesional, zona y modalidad de atencion, disponibilidad, tarifas y calificaciones.', 'El Experto es responsable de mantener está información actualizada. No está permitido publicar información falsa, exagerada o que pueda inducir a error a los Clientes.'] },
  { h: '3. Experiencia y formación profesional', p: ['El Experto podrá informar su experiencia laboral, formación académica, certificaciones, licencias, conocimientos y demás credenciales profesionales.', 'Cuando una actividad requiera legalmente tarjeta profesional, matricula, licencia, certificación, registro, permiso o autorización especial, el Experto sera responsable de contar con los requisitos correspondientes antes de ofrecer o prestar dicho servicio.', 'Expertos podrá solicitar documentación para verificar determinada información. La validación realizada por Expertos, cuando exista, no significa que la plataforma garantice la calidad, resultado o idoneidad de los servicios ofrecidos.'] },
  { h: '4. Servicios ofrecidos', p: ['Cada Experto debe describir claramente los servicios que ofrece. La descripción deberá permitir al Cliente comprender, como mínimo:'], ul: ['Que servicio ofrece.', 'Que incluye.', 'Que no incluye.', 'Que necesita del Cliente.', 'Tiempo estimado de realización, cuando corresponda.', 'Modalidad de prestación.', 'Lugar o cobertura geográfica, cuando aplique.', 'Precio o forma de cotización, cuando corresponda.', 'Entregables, cuando existan.'], p2: ['El Experto no deberá publicar servicios diferentes de aquellos que realmente puede prestar.'] },
  { h: '5. Libertad para establecer las condiciones del servicio', p: ['Expertos no obliga a utilizar una única modalidad de contratación. El Experto y el Cliente podrán acordar, segun corresponda:'], ul: ['Precio.', 'Duración.', 'Número de sesiones.', 'Alcance.', 'Fechas.', 'Horarios.', 'Modalidad presencial o virtual.', 'Entregables.', 'Forma de pago.', 'Condiciones de cancelación.', 'Otras condiciones particulares.'], p2: ['Las condiciones acordadas deberán ser claras para ambas partes antes de iniciar el servicio. Cuando Expertos disponga de herramientas específicas para contratación o pago, deberán respetarse las condiciones de uso de dichas herramientas.'] },
  { h: '6. Comunicacion con los Clientes', p: ['El Experto deberá mantener una comunicación profesional, respetuosa y clara. No está permitido:'], ul: ['Insultar.', 'Amenazar.', 'Hostigar.', 'Discriminar.', 'Acosar.', 'Engañar.', 'Presionar indebidamente a un Cliente.', 'Solicitar información innecesaria o excesivamente sensible.'], p2: ['El Experto deberá utilizar la información de contacto de los Clientes únicamente para fines relacionados con el servicio o con otros fines que hayan sido debidamente autorizados.'] },
  { h: '7. Proteccion de la información del Cliente', p: ['La información recibida de un Cliente debe tratarse de manera confidencial cuando por su naturaleza, acuerdo o legislación aplicable así corresponda. El Experto no podrá:'], ul: ['Compartir información del Cliente con terceros sin autorización cuando está sea necesaria.', 'Publicar conversaciones privadas.', 'Utilizar documentos del Cliente para otros fines.', 'Vender información obtenida a través de Expertos.', 'Utilizar información del Cliente para campañas no autorizadas.', 'Almacenar información sensible de manera insegura.'], p2: ['Cuando el servicio implique el tratamiento de datos personales por parte del Experto, este deberá cumplir las obligaciones legales que le sean aplicables.'] },
  { h: '8. Uso responsable de documentos e información', p: ['Si el Cliente proporciona documentos, fotografías, bases de datos, archivos, contratos, información financiera, empresarial, personal, código fuente, diseños o material protegido por derechos de autor, el Experto deberá utilizarlos únicamente para las finalidades relacionadas con el servicio acordado, salvo autorización diferente.', 'El Experto deberá adoptar medidas razonables para evitar pérdida, filtración, acceso no autorizado o divulgación de dicha información.'] },
  { h: '9. Propiedad intelectual', p: ['El Experto debe respetar los derechos de propiedad intelectual de terceros. No podrá ofrecer como propio:'], ul: ['Diseños creados por otra persona.', 'Fotografias protegidas.', 'Textos copiados.', 'Software sin autorización.', 'Plantillas cuyo uso no este permitido.', 'Marcas de terceros.', 'Trabajos realizados por otras personas.'], p2: ['Cuando el servicio implique creacion de contenido, software, diseños, documentos u otros materiales, el Cliente y el Experto deberán acordar las condiciones de uso, licencia o transferencia de derechos que correspondan.'] },
  { h: '10. Uso de inteligencia artificial', p: ['Cuando el Experto utilice herramientas de inteligencia artificial para prestar un servicio, deberá hacerlo de manera responsable y respetando derechos de autor, confidencialidad, protección de datos, información privada del Cliente y las condiciones acordadas con el Cliente.', 'El Experto no deberá introducir información confidencial o datos personales del Cliente en herramientas de terceros cuando no cuente con autorización o cuando hacerlo pueda comprometer la seguridad de dicha información.', 'Cuando la naturaleza del servicio lo haga relevante, el Experto deberá informar al Cliente sobre el uso sustancial de herramientas de inteligencia artificial.'] },
  { h: '11. Prohibicion de suplantación', p: ['Esta prohibido:'], ul: ['Crear un perfil utilizando la identidad de otra persona.', 'Utilizar fotografías de terceros como si fueran propias.', 'Presentar experiencia profesional perteneciente a otra persona.', 'Utilizar certificaciones falsas.', 'Utilizar documentos falsificados.', 'Hacerse pasar por una empresa o profesional sin autorización.'], p2: ['Expertos podrá suspender inmediatamente una cuenta cuando existan indicios razonables de suplantación o fraude.'] },
  { h: '12. Prohibicion de información falsa', p: ['El Experto no podrá afirmar que:'], ul: ['Tiene titulos que no posee.', 'Tiene certificaciones que no tiene.', 'Ha trabajado para empresas con las que nunca trabajo.', 'Tiene determinada experiencia cuando no puede respaldarla.', 'Esta autorizado para ejercer una profesión cuando legalmente no lo está.', 'Puede garantizar resultados que razonablemente no puede garantizar.'], p2: ['La información profesional debe ser verificable cuando Expertos o un Cliente solicite una comprobacion razonable.'] },
  { h: '13. Servicios prohibidos', p: ['No podrán ofrecerse mediante Expertos servicios que:'], ul: ['Sean ilegales.', 'Faciliten actividades delictivas.', 'Involucren fraude o engaño.', 'Busquen suplantar identidades.', 'Involucren venta o distribucion de bienes o sustancias ilicitas.', 'Busquen vulnerar sistemas informaticos.', 'Faciliten acceso no autorizado a información.', 'Involucren actividades expresamente prohibidas por la legislación.', 'Pongan injustificadamente en riesgo la seguridad de los usuarios.'], p2: ['Expertos podrá establecer categorias adicionales de servicios restringidos o prohibidos de acuerdo con la evolucion de la plataforma y la legislación aplicable.'] },
  { h: '14. Actividades profesionales reguladas', p: ['Cuando el servicio ofrecido corresponda a una actividad profesional regulada por la legislación colombiana, el Experto deberá contar con los requisitos legales necesarios para ejercerla (por ejemplo, matricula profesional, tarjeta profesional, licencia, registro, certificación o permiso de autoridad competente).', 'Expertos podrá solicitar evidencia de estos requisitos antes de permitir la publicación o contratación de determinados servicios.'] },
  { h: '15. Precios y cotizaciones', p: ['El Experto deberá informar los precios de manera clara cuando decida publicarlos.', 'Cuando el precio dependa de las caracteristicas particulares del servicio, podrá indicar "Solicitar cotización". En ese caso, deberá explicar al Cliente los factores que pueden modificar el precio.', 'No está permitido modificar injustificadamente el precio despues de que el Cliente haya aceptado una propuesta, salvo que exista una nueva condición acordada entre ambas partes.'] },
  { h: '16. Pagos', p: ['Cuando Expertos disponga de mecanismos de pago dentro de la plataforma, el Experto deberá cumplir las condiciones establecidas para dichos mecanismos.', 'Cuando el pago sea acordado directamente entre Cliente y Experto, las partes seran responsables de cumplir las condiciones pactadas y las obligaciones legales correspondientes.', 'El Experto deberá informar de manera clara cualquier costo adicional que pueda generarse antes de que el Cliente acepte el servicio.'] },
  { h: '17. Cancelaciones', p: ['Las condiciones de cancelación deberán ser informadas antes de iniciar el servicio cuando sea necesario. El Experto deberá evitar cancelaciones injustificadas.', 'Cuando no pueda cumplir con un servicio previamente acordado, deberá informar al Cliente tan pronto como sea posible y procurar una solución razonable.', 'Si Expertos dispone de reglas específicas de cancelación o reembolso para determinadas operaciones, estas prevaleceran sobre las condiciones generales cuando sean aplicables.'] },
  { h: '18. Cumplimiento de los servicios', p: ['El Experto deberá prestar el servicio de acuerdo con las condiciones acordadas con el Cliente. No deberá:'], ul: ['Entregar deliberadamente un trabajo diferente al acordado.', 'Ocultar limitaciones importantes.', 'Retrasar injustificadamente el servicio.', 'Abandonar un proyecto sin comunicación.', 'Utilizar material no autorizado.', 'Delegar el servicio a otra persona sin informar cuando esto sea relevante para el acuerdo.'], p2: ['Si por circunstancias razonables debe modificar el alcance del servicio, deberá comunicarlo y obtener la aceptación correspondiente cuando sea necesario.'] },
  { h: '19. Subcontratacion', p: ['El Experto no deberá transferir o subcontratar un servicio a otra persona cuando el Cliente haya contratado especificamente sus conocimientos o experiencia personal, salvo que el Cliente lo autorice o las condiciones del servicio permitan expresamente dicha modalidad.', 'El Experto sera responsable de las obligaciones que asuma frente al Cliente en los terminos acordados y de acuerdo con la legislación aplicable.'] },
  { h: '20. Calificaciones y reseñas', p: ['Los Clientes podrán calificar los servicios recibidos cuando está funcionalidad este disponible. Las calificaciones deberán corresponder a experiencias reales. El Experto no podrá:'], ul: ['Comprar calificaciones.', 'Crear cuentas falsas para calificarse.', 'Solicitar calificaciones engañosas.', 'Amenazar a un Cliente para obtener una calificación positiva.', 'Ofrecer beneficios indebidos a cambio de una determinada calificación.'], p2: ['Expertos podrá revisar y retirar calificaciones que infrinjan las reglas de la plataforma.'] },
  { h: '21. Contacto fuera de la plataforma', p: ['Los usuarios podrán establecer contacto fuera de Expertos cuando esto sea permitido por las funcionalidades y reglas de la plataforma. Sin embargo, está prohibido utilizar la información obtenida dentro de Expertos para:'], ul: ['Enviar publicidad no solicitada.', 'Acosar al Cliente.', 'Realizar actividades fraudulentas.', 'Obtener información adicional sin autorización.', 'Realizar actividades diferentes de aquellas relacionadas con el servicio.'], p2: ['Cuando Expertos proporcione mecanismos de contratación, pago, protección o gestión de servicios, podrá establecer reglas específicas sobre el uso de dichos mecanismos.'] },
  { h: '22. No manipulacion de la plataforma', p: ['El Experto no podrá utilizar mecanismos destinados a manipular resultados de búsqueda, calificaciones, número de solicitudes, visibilidad del perfil, estadisticas, recomendaciones o sistemas de reputación.', 'Tampoco podrá utilizar bots, scripts o herramientas automatizadas para interactuar con la plataforma sin autorización.'] },
  { h: '23. Seguridad de la cuenta', p: ['El Experto debe mantener seguras sus credenciales. Si sospecha que alguien ha obtenido acceso a su cuenta, deberá informar a Expertos inmediatamente.', 'El Experto no deberá compartir contraseña, códigos de autenticación, tokens, llaves de acceso ni información de recuperación.'] },
  { h: '24. Responsabilidad profesional', p: ['Cada Experto es responsable de los servicios que ofrece y de cumplir las obligaciones legales, tributarias, profesionales y comerciales que correspondan a su actividad.', 'Expertos no garantiza que todos los Expertos tengan determinado nivel de experiencia o que los servicios contratados produzcan un resultado específico.', 'La información disponible en los perfiles deberá ser evaluada por el Cliente antes de contratar.'] },
  { h: '25. Conflictos entre Cliente y Experto', p: ['Expertos podrá ofrecer mecanismos de comunicación, soporte o gestión de conflictos cuando estos estén disponibles. Los usuarios deberán intentar resolver sus diferencias de manera respetuosa.', 'Cuando corresponda, Expertos podrá solicitar información relacionada con el servicio para analizar una reclamación, siempre respetando las obligaciones aplicables en materia de protección de datos.', 'La participación de Expertos en una controversia no implica necesariamente que la plataforma asuma responsabilidad por el servicio prestado por un Experto.'] },
  { h: '26. Sistema de verificación', p: ['Expertos podrá implementar diferentes niveles de verificación, por ejemplo:'], ul: ['Perfil registrado: el usuario creo una cuenta y proporciono la información requerida.', 'Identidad verificada: Expertos realizo un proceso de validación de identidad utilizando los mecanismos disponibles.', 'Experiencia verificada: determinada información profesional fue revisada mediante documentación o mecanismos definidos por Expertos.', 'Credencial verificada: una certificación, licencia, matricula u otro documento profesional fue validado cuando corresponda.'], p2: ['Los distintivos de verificación no deberán interpretarse como una garantía absoluta sobre la calidad del servicio.'] },
  { h: '27. Uso de la marca Expertos', p: ['El Experto podrá utilizar los elementos de identificación proporcionados por Expertos únicamente de acuerdo con las reglas de la plataforma. No podrá:'], ul: ['Modificar el logotipo de Expertos para crear una marca engañosa.', 'Presentarse como empleado de Expertos cuando no lo sea.', 'Afirmar que Expertos garantiza personalmente sus servicios cuando no exista tal garantía.', 'Utilizar la marca Expertos para actividades ajenas a la plataforma.'] },
  { h: '28. Suspension del perfil', p: ['Expertos podrá suspender temporalmente un perfil cuando se detecte información potencialmente falsa, exista una investigacion por incumplimiento, se presenten reclamaciones que requieran revision, exista un riesgo de seguridad, se detecte actividad sospechosa, o el Experto incumpla estas reglas.', 'Cuando resulte procedente, se informara al Experto sobre la situación y los pasos necesarios para resolverla.'] },
  { h: '29. Cancelacion definitiva', p: ['Expertos podrá cancelar definitivamente una cuenta cuando exista un incumplimiento grave o reiterado de los Terminos de Uso, estas Reglas para Expertos, la legislación aplicable o las normas de seguridad de la plataforma.', 'Entre otros casos, podrán considerarse incumplimientos graves: fraude, suplantación, falsificacion de documentos, amenazas, acoso, uso indebido de datos personales, actividades ilegales, intentos de comprometer la seguridad de la plataforma, y reincidencia en incumplimientos.'] },
  { h: '30. Solicitud de revision', p: ['Cuando una cuenta haya sido suspendida o limitada, el Experto podrá solicitar una revision mediante los canales habilitados por Expertos.', 'La solicitud deberá explicar las circunstancias y, cuando corresponda, aportar información o documentación relevante.', 'Expertos podrá mantener la medida cuando existan razones suficientes para ello.'] },
  { h: '31. Cambios en estas reglas', p: ['Expertos podrá actualizar estas reglas para reflejar cambios en la legislación, la tecnologia, las funcionalidades de la plataforma, el modelo de negocio, las politicas de seguridad o las necesidades de la comunidad.', 'La version vigente estara disponible en la Plataforma e indicara su fecha de actualización.'] },
  { h: '32. Aceptacion', p: ['Al registrarse como Experto, el usuario declara que:'], ul: ['La información suministrada es verdadera.', 'Tiene derecho a ofrecer los servicios publicados.', 'Cumplira la legislación aplicable a su actividad.', 'Respetara a los Clientes.', 'Protegera la información que reciba.', 'Cumplira los Terminos de Uso de Expertos.', 'Cumplira la Politica de Tratamiento de Datos Personales.', 'Cumplira estas Reglas para Expertos.'] }
]

function ReglasExpertos() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Header />

      <div className="p-6 max-w-2xl mx-auto">
        <h2 className="text-2xl font-bold text-[#2C3E50] mb-1">Reglas para Expertos de Expertos</h2>
        <p className="text-sm text-gray-500 mb-6">Ultima actualización: [FECHA]</p>

        <p className="text-gray-700 text-sm mb-6">
          Estas Reglas para Expertos establecen las condiciones específicas que deben cumplir las personas
          naturales o juridicas que ofrecen servicios profesionales a través de Expertos. Al registrarse
          como Experto, crear un perfil, publicar un servicio o utilizar las funcionalidades destinadas a
          profesionales, el usuario declara que ha leido y acepta estas reglas, ademas de los Terminos de
          Uso y la Politica de Tratamiento de Datos Personales de Expertos.
        </p>

        <div className="flex flex-col gap-5 text-gray-700 text-sm leading-relaxed">
          {secciones.map((sección) => (
            <section key={sección.h}>
              <h3 className="font-bold text-[#2C3E50] mb-1">{sección.h}</h3>
              {sección.p && sección.p.map((texto, i) => <p key={i} className="mb-1">{texto}</p>)}
              {sección.ul && (
                <ul className="list-disc list-inside mb-1">
                  {sección.ul.map((item, i) => <li key={i}>{item}</li>)}
                </ul>
              )}
              {sección.p2 && sección.p2.map((texto, i) => <p key={i} className="mb-1">{texto}</p>)}
            </section>
          ))}

          <p className="font-bold text-[#2C3E50] mt-2">
            Expertos podrá actualizar estas reglas y establecer requisitos adicionales cuando sean
            necesarios para mantener la seguridad, confianza y calidad de la plataforma.
          </p>

          <section>
            <h3 className="font-bold text-[#2C3E50] mb-1">Contacto</h3>
            <p>Para preguntas relacionadas con estas reglas:</p>
            <ul className="list-disc list-inside">
              <li>Correo: [CORREO]</li>
              <li>Responsable: [NOMBRE LEGAL]</li>
              <li>NIT: [NIT]</li>
              <li>Dirección: [DIRECCION]</li>
              <li>Ciudad: [CIUDAD, COLOMBIA]</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  )
}

export default ReglasExpertos