import Header from './Header'

const secciones = [
  { h: '1. ¿Que significa ser Experto?', p: ['Un Experto es una persona natural o juridica que utiliza la plataforma Expertos para presentar sus conocimientos, experiencia, habilidades o servicios profesionales y conectarse con personas o empresas que puedan requerirlos.', 'Ser Experto dentro de la plataforma no significa que Expertos sea su empleador, representante, socio, agente o subordinado.', 'Cada Experto presta sus servicios de manera independiente y es responsable de las obligaciones que se deriven de su actividad profesional.'] },
  { h: '2. Informacion del perfil', p: ['El Experto debe proporcionar informacion:'], ul: ['Verdadera.', 'Completa.', 'Clara.', 'Actualizada.', 'Comprobable cuando corresponda.'], p2: ['El perfil podra incluir informacion como nombre, fotografia, profesion, experiencia, formacion academica, especialidades, habilidades, certificaciones, servicios ofrecidos, portafolio, descripcion profesional, zona y modalidad de atencion, disponibilidad, tarifas y calificaciones.', 'El Experto es responsable de mantener esta informacion actualizada. No esta permitido publicar informacion falsa, exagerada o que pueda inducir a error a los Clientes.'] },
  { h: '3. Experiencia y formacion profesional', p: ['El Experto podra informar su experiencia laboral, formacion academica, certificaciones, licencias, conocimientos y demas credenciales profesionales.', 'Cuando una actividad requiera legalmente tarjeta profesional, matricula, licencia, certificacion, registro, permiso o autorizacion especial, el Experto sera responsable de contar con los requisitos correspondientes antes de ofrecer o prestar dicho servicio.', 'Expertos podra solicitar documentacion para verificar determinada informacion. La validacion realizada por Expertos, cuando exista, no significa que la plataforma garantice la calidad, resultado o idoneidad de los servicios ofrecidos.'] },
  { h: '4. Servicios ofrecidos', p: ['Cada Experto debe describir claramente los servicios que ofrece. La descripcion debera permitir al Cliente comprender, como minimo:'], ul: ['Que servicio ofrece.', 'Que incluye.', 'Que no incluye.', 'Que necesita del Cliente.', 'Tiempo estimado de realizacion, cuando corresponda.', 'Modalidad de prestacion.', 'Lugar o cobertura geografica, cuando aplique.', 'Precio o forma de cotizacion, cuando corresponda.', 'Entregables, cuando existan.'], p2: ['El Experto no debera publicar servicios diferentes de aquellos que realmente puede prestar.'] },
  { h: '5. Libertad para establecer las condiciones del servicio', p: ['Expertos no obliga a utilizar una unica modalidad de contratacion. El Experto y el Cliente podran acordar, segun corresponda:'], ul: ['Precio.', 'Duracion.', 'Numero de sesiones.', 'Alcance.', 'Fechas.', 'Horarios.', 'Modalidad presencial o virtual.', 'Entregables.', 'Forma de pago.', 'Condiciones de cancelacion.', 'Otras condiciones particulares.'], p2: ['Las condiciones acordadas deberan ser claras para ambas partes antes de iniciar el servicio. Cuando Expertos disponga de herramientas especificas para contratacion o pago, deberan respetarse las condiciones de uso de dichas herramientas.'] },
  { h: '6. Comunicacion con los Clientes', p: ['El Experto debera mantener una comunicacion profesional, respetuosa y clara. No esta permitido:'], ul: ['Insultar.', 'Amenazar.', 'Hostigar.', 'Discriminar.', 'Acosar.', 'Engañar.', 'Presionar indebidamente a un Cliente.', 'Solicitar informacion innecesaria o excesivamente sensible.'], p2: ['El Experto debera utilizar la informacion de contacto de los Clientes unicamente para fines relacionados con el servicio o con otros fines que hayan sido debidamente autorizados.'] },
  { h: '7. Proteccion de la informacion del Cliente', p: ['La informacion recibida de un Cliente debe tratarse de manera confidencial cuando por su naturaleza, acuerdo o legislacion aplicable asi corresponda. El Experto no podra:'], ul: ['Compartir informacion del Cliente con terceros sin autorizacion cuando esta sea necesaria.', 'Publicar conversaciones privadas.', 'Utilizar documentos del Cliente para otros fines.', 'Vender informacion obtenida a traves de Expertos.', 'Utilizar informacion del Cliente para campañas no autorizadas.', 'Almacenar informacion sensible de manera insegura.'], p2: ['Cuando el servicio implique el tratamiento de datos personales por parte del Experto, este debera cumplir las obligaciones legales que le sean aplicables.'] },
  { h: '8. Uso responsable de documentos e informacion', p: ['Si el Cliente proporciona documentos, fotografias, bases de datos, archivos, contratos, informacion financiera, empresarial, personal, codigo fuente, diseños o material protegido por derechos de autor, el Experto debera utilizarlos unicamente para las finalidades relacionadas con el servicio acordado, salvo autorizacion diferente.', 'El Experto debera adoptar medidas razonables para evitar perdida, filtracion, acceso no autorizado o divulgacion de dicha informacion.'] },
  { h: '9. Propiedad intelectual', p: ['El Experto debe respetar los derechos de propiedad intelectual de terceros. No podra ofrecer como propio:'], ul: ['Diseños creados por otra persona.', 'Fotografias protegidas.', 'Textos copiados.', 'Software sin autorizacion.', 'Plantillas cuyo uso no este permitido.', 'Marcas de terceros.', 'Trabajos realizados por otras personas.'], p2: ['Cuando el servicio implique creacion de contenido, software, diseños, documentos u otros materiales, el Cliente y el Experto deberan acordar las condiciones de uso, licencia o transferencia de derechos que correspondan.'] },
  { h: '10. Uso de inteligencia artificial', p: ['Cuando el Experto utilice herramientas de inteligencia artificial para prestar un servicio, debera hacerlo de manera responsable y respetando derechos de autor, confidencialidad, proteccion de datos, informacion privada del Cliente y las condiciones acordadas con el Cliente.', 'El Experto no debera introducir informacion confidencial o datos personales del Cliente en herramientas de terceros cuando no cuente con autorizacion o cuando hacerlo pueda comprometer la seguridad de dicha informacion.', 'Cuando la naturaleza del servicio lo haga relevante, el Experto debera informar al Cliente sobre el uso sustancial de herramientas de inteligencia artificial.'] },
  { h: '11. Prohibicion de suplantacion', p: ['Esta prohibido:'], ul: ['Crear un perfil utilizando la identidad de otra persona.', 'Utilizar fotografias de terceros como si fueran propias.', 'Presentar experiencia profesional perteneciente a otra persona.', 'Utilizar certificaciones falsas.', 'Utilizar documentos falsificados.', 'Hacerse pasar por una empresa o profesional sin autorizacion.'], p2: ['Expertos podra suspender inmediatamente una cuenta cuando existan indicios razonables de suplantacion o fraude.'] },
  { h: '12. Prohibicion de informacion falsa', p: ['El Experto no podra afirmar que:'], ul: ['Tiene titulos que no posee.', 'Tiene certificaciones que no tiene.', 'Ha trabajado para empresas con las que nunca trabajo.', 'Tiene determinada experiencia cuando no puede respaldarla.', 'Esta autorizado para ejercer una profesion cuando legalmente no lo esta.', 'Puede garantizar resultados que razonablemente no puede garantizar.'], p2: ['La informacion profesional debe ser verificable cuando Expertos o un Cliente solicite una comprobacion razonable.'] },
  { h: '13. Servicios prohibidos', p: ['No podran ofrecerse mediante Expertos servicios que:'], ul: ['Sean ilegales.', 'Faciliten actividades delictivas.', 'Involucren fraude o engaño.', 'Busquen suplantar identidades.', 'Involucren venta o distribucion de bienes o sustancias ilicitas.', 'Busquen vulnerar sistemas informaticos.', 'Faciliten acceso no autorizado a informacion.', 'Involucren actividades expresamente prohibidas por la legislacion.', 'Pongan injustificadamente en riesgo la seguridad de los usuarios.'], p2: ['Expertos podra establecer categorias adicionales de servicios restringidos o prohibidos de acuerdo con la evolucion de la plataforma y la legislacion aplicable.'] },
  { h: '14. Actividades profesionales reguladas', p: ['Cuando el servicio ofrecido corresponda a una actividad profesional regulada por la legislacion colombiana, el Experto debera contar con los requisitos legales necesarios para ejercerla (por ejemplo, matricula profesional, tarjeta profesional, licencia, registro, certificacion o permiso de autoridad competente).', 'Expertos podra solicitar evidencia de estos requisitos antes de permitir la publicacion o contratacion de determinados servicios.'] },
  { h: '15. Precios y cotizaciones', p: ['El Experto debera informar los precios de manera clara cuando decida publicarlos.', 'Cuando el precio dependa de las caracteristicas particulares del servicio, podra indicar "Solicitar cotizacion". En ese caso, debera explicar al Cliente los factores que pueden modificar el precio.', 'No esta permitido modificar injustificadamente el precio despues de que el Cliente haya aceptado una propuesta, salvo que exista una nueva condicion acordada entre ambas partes.'] },
  { h: '16. Pagos', p: ['Cuando Expertos disponga de mecanismos de pago dentro de la plataforma, el Experto debera cumplir las condiciones establecidas para dichos mecanismos.', 'Cuando el pago sea acordado directamente entre Cliente y Experto, las partes seran responsables de cumplir las condiciones pactadas y las obligaciones legales correspondientes.', 'El Experto debera informar de manera clara cualquier costo adicional que pueda generarse antes de que el Cliente acepte el servicio.'] },
  { h: '17. Cancelaciones', p: ['Las condiciones de cancelacion deberan ser informadas antes de iniciar el servicio cuando sea necesario. El Experto debera evitar cancelaciones injustificadas.', 'Cuando no pueda cumplir con un servicio previamente acordado, debera informar al Cliente tan pronto como sea posible y procurar una solucion razonable.', 'Si Expertos dispone de reglas especificas de cancelacion o reembolso para determinadas operaciones, estas prevaleceran sobre las condiciones generales cuando sean aplicables.'] },
  { h: '18. Cumplimiento de los servicios', p: ['El Experto debera prestar el servicio de acuerdo con las condiciones acordadas con el Cliente. No debera:'], ul: ['Entregar deliberadamente un trabajo diferente al acordado.', 'Ocultar limitaciones importantes.', 'Retrasar injustificadamente el servicio.', 'Abandonar un proyecto sin comunicacion.', 'Utilizar material no autorizado.', 'Delegar el servicio a otra persona sin informar cuando esto sea relevante para el acuerdo.'], p2: ['Si por circunstancias razonables debe modificar el alcance del servicio, debera comunicarlo y obtener la aceptacion correspondiente cuando sea necesario.'] },
  { h: '19. Subcontratacion', p: ['El Experto no debera transferir o subcontratar un servicio a otra persona cuando el Cliente haya contratado especificamente sus conocimientos o experiencia personal, salvo que el Cliente lo autorice o las condiciones del servicio permitan expresamente dicha modalidad.', 'El Experto sera responsable de las obligaciones que asuma frente al Cliente en los terminos acordados y de acuerdo con la legislacion aplicable.'] },
  { h: '20. Calificaciones y reseñas', p: ['Los Clientes podran calificar los servicios recibidos cuando esta funcionalidad este disponible. Las calificaciones deberan corresponder a experiencias reales. El Experto no podra:'], ul: ['Comprar calificaciones.', 'Crear cuentas falsas para calificarse.', 'Solicitar calificaciones engañosas.', 'Amenazar a un Cliente para obtener una calificacion positiva.', 'Ofrecer beneficios indebidos a cambio de una determinada calificacion.'], p2: ['Expertos podra revisar y retirar calificaciones que infrinjan las reglas de la plataforma.'] },
  { h: '21. Contacto fuera de la plataforma', p: ['Los usuarios podran establecer contacto fuera de Expertos cuando esto sea permitido por las funcionalidades y reglas de la plataforma. Sin embargo, esta prohibido utilizar la informacion obtenida dentro de Expertos para:'], ul: ['Enviar publicidad no solicitada.', 'Acosar al Cliente.', 'Realizar actividades fraudulentas.', 'Obtener informacion adicional sin autorizacion.', 'Realizar actividades diferentes de aquellas relacionadas con el servicio.'], p2: ['Cuando Expertos proporcione mecanismos de contratacion, pago, proteccion o gestion de servicios, podra establecer reglas especificas sobre el uso de dichos mecanismos.'] },
  { h: '22. No manipulacion de la plataforma', p: ['El Experto no podra utilizar mecanismos destinados a manipular resultados de busqueda, calificaciones, numero de solicitudes, visibilidad del perfil, estadisticas, recomendaciones o sistemas de reputacion.', 'Tampoco podra utilizar bots, scripts o herramientas automatizadas para interactuar con la plataforma sin autorizacion.'] },
  { h: '23. Seguridad de la cuenta', p: ['El Experto debe mantener seguras sus credenciales. Si sospecha que alguien ha obtenido acceso a su cuenta, debera informar a Expertos inmediatamente.', 'El Experto no debera compartir contraseña, codigos de autenticacion, tokens, llaves de acceso ni informacion de recuperacion.'] },
  { h: '24. Responsabilidad profesional', p: ['Cada Experto es responsable de los servicios que ofrece y de cumplir las obligaciones legales, tributarias, profesionales y comerciales que correspondan a su actividad.', 'Expertos no garantiza que todos los Expertos tengan determinado nivel de experiencia o que los servicios contratados produzcan un resultado especifico.', 'La informacion disponible en los perfiles debera ser evaluada por el Cliente antes de contratar.'] },
  { h: '25. Conflictos entre Cliente y Experto', p: ['Expertos podra ofrecer mecanismos de comunicacion, soporte o gestion de conflictos cuando estos esten disponibles. Los usuarios deberan intentar resolver sus diferencias de manera respetuosa.', 'Cuando corresponda, Expertos podra solicitar informacion relacionada con el servicio para analizar una reclamacion, siempre respetando las obligaciones aplicables en materia de proteccion de datos.', 'La participacion de Expertos en una controversia no implica necesariamente que la plataforma asuma responsabilidad por el servicio prestado por un Experto.'] },
  { h: '26. Sistema de verificacion', p: ['Expertos podra implementar diferentes niveles de verificacion, por ejemplo:'], ul: ['Perfil registrado: el usuario creo una cuenta y proporciono la informacion requerida.', 'Identidad verificada: Expertos realizo un proceso de validacion de identidad utilizando los mecanismos disponibles.', 'Experiencia verificada: determinada informacion profesional fue revisada mediante documentacion o mecanismos definidos por Expertos.', 'Credencial verificada: una certificacion, licencia, matricula u otro documento profesional fue validado cuando corresponda.'], p2: ['Los distintivos de verificacion no deberan interpretarse como una garantia absoluta sobre la calidad del servicio.'] },
  { h: '27. Uso de la marca Expertos', p: ['El Experto podra utilizar los elementos de identificacion proporcionados por Expertos unicamente de acuerdo con las reglas de la plataforma. No podra:'], ul: ['Modificar el logotipo de Expertos para crear una marca engañosa.', 'Presentarse como empleado de Expertos cuando no lo sea.', 'Afirmar que Expertos garantiza personalmente sus servicios cuando no exista tal garantia.', 'Utilizar la marca Expertos para actividades ajenas a la plataforma.'] },
  { h: '28. Suspension del perfil', p: ['Expertos podra suspender temporalmente un perfil cuando se detecte informacion potencialmente falsa, exista una investigacion por incumplimiento, se presenten reclamaciones que requieran revision, exista un riesgo de seguridad, se detecte actividad sospechosa, o el Experto incumpla estas reglas.', 'Cuando resulte procedente, se informara al Experto sobre la situacion y los pasos necesarios para resolverla.'] },
  { h: '29. Cancelacion definitiva', p: ['Expertos podra cancelar definitivamente una cuenta cuando exista un incumplimiento grave o reiterado de los Terminos de Uso, estas Reglas para Expertos, la legislacion aplicable o las normas de seguridad de la plataforma.', 'Entre otros casos, podran considerarse incumplimientos graves: fraude, suplantacion, falsificacion de documentos, amenazas, acoso, uso indebido de datos personales, actividades ilegales, intentos de comprometer la seguridad de la plataforma, y reincidencia en incumplimientos.'] },
  { h: '30. Solicitud de revision', p: ['Cuando una cuenta haya sido suspendida o limitada, el Experto podra solicitar una revision mediante los canales habilitados por Expertos.', 'La solicitud debera explicar las circunstancias y, cuando corresponda, aportar informacion o documentacion relevante.', 'Expertos podra mantener la medida cuando existan razones suficientes para ello.'] },
  { h: '31. Cambios en estas reglas', p: ['Expertos podra actualizar estas reglas para reflejar cambios en la legislacion, la tecnologia, las funcionalidades de la plataforma, el modelo de negocio, las politicas de seguridad o las necesidades de la comunidad.', 'La version vigente estara disponible en la Plataforma e indicara su fecha de actualizacion.'] },
  { h: '32. Aceptacion', p: ['Al registrarse como Experto, el usuario declara que:'], ul: ['La informacion suministrada es verdadera.', 'Tiene derecho a ofrecer los servicios publicados.', 'Cumplira la legislacion aplicable a su actividad.', 'Respetara a los Clientes.', 'Protegera la informacion que reciba.', 'Cumplira los Terminos de Uso de Expertos.', 'Cumplira la Politica de Tratamiento de Datos Personales.', 'Cumplira estas Reglas para Expertos.'] }
]

function ReglasExpertos() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Header />

      <div className="p-6 max-w-2xl mx-auto">
        <h2 className="text-2xl font-bold text-[#2C3E50] mb-1">Reglas para Expertos de Expertos</h2>
        <p className="text-sm text-gray-500 mb-6">Ultima actualizacion: [FECHA]</p>

        <p className="text-gray-700 text-sm mb-6">
          Estas Reglas para Expertos establecen las condiciones especificas que deben cumplir las personas
          naturales o juridicas que ofrecen servicios profesionales a traves de Expertos. Al registrarse
          como Experto, crear un perfil, publicar un servicio o utilizar las funcionalidades destinadas a
          profesionales, el usuario declara que ha leido y acepta estas reglas, ademas de los Terminos de
          Uso y la Politica de Tratamiento de Datos Personales de Expertos.
        </p>

        <div className="flex flex-col gap-5 text-gray-700 text-sm leading-relaxed">
          {secciones.map((seccion) => (
            <section key={seccion.h}>
              <h3 className="font-bold text-[#2C3E50] mb-1">{seccion.h}</h3>
              {seccion.p && seccion.p.map((texto, i) => <p key={i} className="mb-1">{texto}</p>)}
              {seccion.ul && (
                <ul className="list-disc list-inside mb-1">
                  {seccion.ul.map((item, i) => <li key={i}>{item}</li>)}
                </ul>
              )}
              {seccion.p2 && seccion.p2.map((texto, i) => <p key={i} className="mb-1">{texto}</p>)}
            </section>
          ))}

          <p className="font-bold text-[#2C3E50] mt-2">
            Expertos podra actualizar estas reglas y establecer requisitos adicionales cuando sean
            necesarios para mantener la seguridad, confianza y calidad de la plataforma.
          </p>

          <section>
            <h3 className="font-bold text-[#2C3E50] mb-1">Contacto</h3>
            <p>Para preguntas relacionadas con estas reglas:</p>
            <ul className="list-disc list-inside">
              <li>Correo: [CORREO]</li>
              <li>Responsable: [NOMBRE LEGAL]</li>
              <li>NIT: [NIT]</li>
              <li>Direccion: [DIRECCION]</li>
              <li>Ciudad: [CIUDAD, COLOMBIA]</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  )
}

export default ReglasExpertos